### ISSUE TITLE
Loading weight file dut_omron416.h5 gives ValueError

### ISSUE THREAD

**Issue by pyrator** [anish9/GCPAnet-tensorflow2.x#1]
Getting ValueError: You are trying to load a weight file containing 164 layers into a model with 162 layers. I'm using dut_omron416.h5
pip show tensorflow
Name: tensorflow
Version: 2.2.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: c:\users\keith\appdata\roaming\python\python37\site-packages
Requires: google-pasta, gast, tensorflow-estimator, tensorboard, keras-preprocessing, absl-py, wrapt, scipy, wheel, six, h5py, termcolor, grpcio, protobuf, astunparse, opt-einsum, numpy

**Comment by anish9** [comment]
@pyrator  let me know now if it is working

**Comment by pyrator** [comment]
Yes thanks though the line cv2.imshow(prediction) I changed to cv2.imshow('',prediction) in infer.py. I have opencv 4.2 installed.
